#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

# new path
export PATH=$PATH:~/.bin/

# for starting i3
if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
      exec startx
fi
